name: iOS CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build & Test
      run: |
        xcodebuild build -scheme YourApp -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
